steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  env:
    - DOCKER_BUILDKIT=1
  args: [
    '-c',
    "eval $(echo docker build . --build-arg 'DEFAULT_JSON=\"$$DEFAULT_JSON\"' -t europe-west1-docker.pkg.dev/$PROJECT_ID/dtu-mlops-project/gcp_app:latest -f dockerfiles/api.dockerfile)"
  ]
  secretEnv: ['DEFAULT_JSON']

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/dtu-mlops-project/gcp_app:latest'
  ]

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Deploy to Cloud Run'
  args: [
    'run',
    'deploy',
    'gcp-app',
    '--image',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/dtu-mlops-project/gcp_app:latest',
    '--region',
    'europe-west1',
    '--platform',
    'managed'
  ]

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/secrets/versions/latest
    env: 'DEFAULT_JSON'
