command:
  - python
  - src/mlops_project/train.py
program: src/mlops_project/train.py
name: sweep_hyperparam_optimization
project: mlops_project
method: bayes  # Options: grid, random, bayes
metric:
  name: train_loss  # Metric to minimize/maximize
  goal: minimize
parameters:
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  batch_size:
    values: [8, 16, 32]
  epochs:
    values: [8, 12, 16]
