command:
  - python
  - src/mlops_project/train.py
program: src/mlops_project/train.py
name: sweep_hyperparam_optimization
project: mnist_project
method: bayes  # Options: grid, random, bayes
metric:
  name: train_loss  # Metric to minimize/maximize
  goal: minimize
parameters:
  lr:
    distribution: log_uniform_values
    min: 0.001
    max: 0.1
  batch_size:
    values: [16, 32, 64]
  epochs:
    values: [4, 8]
