steps:
- name: "alpine"
  id: "Replace values in the training config"
  entrypoint: "sh"
  args:
    - '-c'
    - |
      apk add --no-cache gettext
      envsubst < configs/vertex_ai.yaml > configs/vertex_ai.yaml.tmp
      mv configs/vertex_ai.yaml.tmp configs/vertex_ai.yaml
  secretEnv: ['WANDB_API_KEY']

- name: 'alpine'
  id: "Show config"
  waitFor: ['Replace values in the training config']
  entrypoint: "sh"
  args:
    - '-c'
    - |
      cat ${_VERTEX_TRAIN_CONFIG}

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'Run sweep on vertex AI'
  waitFor: ['Replace values in the training config']
  args: [
    'ai',
    'custom-jobs',
    'create',
    '--region',
    'europe-west1',
    '--display-name',
    'wandb-sweep-mlops-job',
    '--config',
    '${_VERTEX_TRAIN_CONFIG}',
  ]
substitutions:
  _VERTEX_TRAIN_CONFIG: 'configs/vertex_ai.yaml'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/wandb-api-key/versions/latest
    env: 'WANDB_API_KEY'
